# Tutorial: Vectors and matrices

In _NumPy_ vector is 1 dimenisonal array where you can store information like data. 

A matrix is a 2 dimenisonal array like a table. It has both rows and columns. In principle you can have multi-dimensional arrays, but we will deal with this later.

To stor numbers in an array to a variable, you can do this in a few ways.

In [3]:
import numpy as np

array_1D = np.array([1, 2, 3, 4, 5])          # generates an 1D array
print(array_1D)
array_2D = np.array([[1, 2, 3], [4, 5, 6]])   # generates a 2x3 2D array
print(array_2D)
array_2D_transpose = array_2D.T               # note ".T" for transpose
print(array_2D_transpose)
array_1D_zero = np.zeros(5)                   # generates an 1D array filled with zeros
print(array_1D_zero)
array_2D_one  = np.ones((3,2))                # generates 3x2 2D array filled with ones, note the "(...)", which is the shape of the array.
print(array_2D_one)
array_1D_random = np.random.rand(3)           # generates 3 random numbers in a 1D array
print(array_1D_random)
array_3D_random = np.random.rand(3,3,3)       # generates 27 random numbers in a 3D array
print(array_3D_random)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[0. 0. 0. 0. 0.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0.4901849  0.82553315 0.9935382 ]
[[[0.68088353 0.22321282 0.66588477]
  [0.77073514 0.12162757 0.48059453]
  [0.64128321 0.20501132 0.06245772]]

 [[0.69623166 0.05840274 0.03601787]
  [0.02573393 0.39035387 0.22349665]
  [0.11906553 0.72043393 0.14957327]]

 [[0.86034796 0.03877555 0.87012305]
  [0.38516853 0.97724629 0.88868807]
  [0.37529149 0.71791645 0.53904947]]]


Note: _np.random.rand_ creates an array of the given shape and populate it with random samples from a uniform distribution over **[0, 1)** (excluding 1).

If you would like to know more _numpy.random_ package, you can have a look [here](https://numpy.org/doc/2.2/reference/random/index.html#module-numpy.random).

To generate evenly spaced values within a given interval the function _np.arange_ is used.

In [4]:
print(np.arange(10))       # generates an array from 0 to 9. Note in Python the default start value is zero and not one.
print(np.arange(1,11))     # of course you can start from one, but then start and end of interval must be provided. Note that the end value is not included (Values are generated within the half-open interval).
print(np.arange(1,11,0.5)) # step size are defined with the third value.
a = np.arange(10) + 1      # generates array from 1 to 10, because we add 1 to the array.
a = a.reshape(5,2)         # reshapes the array to a 2D array with 5 rows and 2 columns.
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


A quick quick way of generating an array is using a function called _np.linspace_. Return evenly spaced numbers over a specified interval (linear). 

In [5]:
print(np.linspace(1,5,5))      # first number is the starting value of the sequence, second number is the end value of the sequence and third number is the number of samples to generate. If no third number is given the default is 50. While the first 2 numbers can have any value the third number must be non-negative.
print(np.linspace(5,-5))       # descending sequence.

[1. 2. 3. 4. 5.]
[ 5.          4.79591837  4.59183673  4.3877551   4.18367347  3.97959184
  3.7755102   3.57142857  3.36734694  3.16326531  2.95918367  2.75510204
  2.55102041  2.34693878  2.14285714  1.93877551  1.73469388  1.53061224
  1.32653061  1.12244898  0.91836735  0.71428571  0.51020408  0.30612245
  0.10204082 -0.10204082 -0.30612245 -0.51020408 -0.71428571 -0.91836735
 -1.12244898 -1.32653061 -1.53061224 -1.73469388 -1.93877551 -2.14285714
 -2.34693878 -2.55102041 -2.75510204 -2.95918367 -3.16326531 -3.36734694
 -3.57142857 -3.7755102  -3.97959184 -4.18367347 -4.3877551  -4.59183673
 -4.79591837 -5.        ]


Note: Evenly spaced numbers in log space can be generated with _np.logspace_.

## Task 1

Create am array,  assigned to the variable **a**, that stores 20 elements. The first element starts at 5 and the last ends at 6 with equal steps in between.

## Task 2
Create an array called **A**, that stores the following values:

1 2 7 2 7 3

## Vector operations

In Python vectors (1D), matrices (2D) and tensors (N-D) are all called arrays. They support multidimensional array algebra, that vectors, matrices and tensors are used for.

Data are often stored in 1D arrays (vectors), e.g. [Task 3](#task-3). You might expect that those data are either stored in a column vector (**Nx1**) or row vector (**1xN**). By default in Python the 1D array is neither **Nx1** nor **1xN**. It is just **N**. Therefore, a _transpose_ on 1D array does nothing. It first this might be a bit confusing, but it comes with many advantages.

In [7]:
a = np.arange(1,4)         # generates an array with [1,2,3]
print(a.shape)             # prints the shape of the array
a_column = a.reshape(3,1)  # reshapes a into column vector
print(a_column)            # prints column vector
print(a_column.shape)      # prints the shape of the array, note the difference to array a
a_row = a.reshape(1,3)     # reshapes a into row vector
print(a_row)               # prints row vector

(3,)
[[1]
 [2]
 [3]]
(3, 1)
[[1 2 3]]


### Vector multiplications

In Python multiplication operation are defined as follow: ``*`` means element-wise multiplication, while ``@`` means matrix multiplication. The differences between ``*`` and ``@`` become more obvious when dealing with multi-dimensional arrays.

Consider the following element-wise multiplication:

```{math}
\begin{bmatrix}
1 & 2 & 3\\
\end{bmatrix}
\begin{bmatrix}
1 & 2 & 3\\
\end{bmatrix}
=
\begin{bmatrix}
1 & 4 & 9\\
\end{bmatrix}
```

or

```{math}
\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}
\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}
=
\begin{bmatrix}
1 \\
4 \\
9 \\
\end{bmatrix}

In [8]:
print(a*a)               # gives an array [1, 4, 9]
print(a_row*a_row)       # gives an row array
print(a_column*a_column) # gives a column array
print(a_row@a_row)       # gives an error message
print(a_column@a_column) # gives an error message

[1 4 9]
[[1 4 9]]
[[1]
 [4]
 [9]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

Let's see what happens when we replace a row with a column vector/array and vice versa.

In [9]:
print(a_row*a_column)   # gives a 3x3 matrix/array
#while
print(a_row@a_column)   # gives a scalar
#or
print(a_column*a_row)   # gives a 3x3 matrix/array
#while
print(a_column@a_row)   # gives a 3x3 matrix/array

[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[14]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


This is all a bit confusing and the results might not be the result, you might have expected.

There are 2 vector multiplication present:

1. row vector times column vector:

```{math}
\begin{bmatrix}
1 & 2 & 3\\
\end{bmatrix}
\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}
=
14
```

This also called a dot product (row times column). See also overview page of this session 2. 

2. column vector times row vector:

```{math}
\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}
\begin{bmatrix}
1 & 2 & 3\\
\end{bmatrix}
=
\begin{bmatrix}
1& 2& 3\\
2& 4& 6\\
3& 6& 9\\
\end{bmatrix}
```

To avoid mistakes and save you having to type a lot of transposes Python defines by default a one-dimensional array of shape N.

In [11]:
# row times column vector
print(np.inner(a,a))  # gives a scalar
#or
print(a@a)            # by default Python treats the vector of shape N before the @ as a row vector and after the @ as a column vector.
# column times row vector
print(np.outer(a,a))  # gives a 3x3 matrix/array

14
14
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In the case of matrices (2D arrays) or N-dimension arrays the differences between between ``*`` and ``@`` are clearer.

In [12]:
m = np.arange(1,5).reshape(2,2) # generates a 2x2 array with values from 1 to 4.
print(m)
print(m*m)                      # element wise multiplication
print(m@m)                      # matrix multiplication, see also overview page for session 2.

[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


## Task 3

Now consider the same square cross sectional rod with an applied force as last week.

|         |  Force [N] | Cross section length [m] |
|:-----|:----:|:------------:|
| sample 1| 2.51E+04   | 0.010|
| sample 2| 2.78E+04   | 0.011|
| sample 3| 2.48E+04   | 0.013|
| sample 4| 2.96E+04   | 0.011|

Create an array for the forces, and one for the cross sectional length. Then use these arrays to calculate the stress on each sample in one line of code.

### Array operations

You can then perform operations on them really quickly.

In [16]:
test = np.array([3,1,2,5,4])      # generate a row vector
print(test)
test_sorted = np.sort(test)       # sorts the elements in an array
print(test_sorted)
#or
test.sort()
print(test)
average = np.mean(test)           # gives the average of all the values
print(average)
#or
average = test.mean()
print(average)
min_value = np.min(test)          # gives minimum value of an array
print(min_value)
#or
min_value = test.min()            # of course this also works for max() and many other functions
print(min_value)
times2=test*2                     # multiply each element by 2
print(times2)
sqrd=test**2                      # square each elemnt. Note mathematical operators are element-wise.
print(sqrd)

[3 1 2 5 4]
[1 2 3 4 5]
[1 2 3 4 5]
3.0
3.0
1
1
[ 2  4  6  8 10]
[ 1  4  9 16 25]


Calculate the mean value of your stresses from [Task 3](#task-3).

## Task 4

Create an array called **A** that stores 5 random numbers (use np.random.rand). Multiple each value by 10. Use _np.round_ to round the value to 1dp.

Can you do this in one line of code?

Use the help function, e.g. _np.round?_ to look up, how this is down.

Can you also do it with _A.round_?

## Matrices

A matrix is a way of storing information using both rows and columns (two dimensions).

## Creating a matrix: part 1
You first give number of columns (they go across), then rows (which go down). You can set up matrices in a number of ways. The first to generate a matrix using quick functions or the second to generate an 1D array and then reshape it.

In [17]:
m = 3                              # set up a value of m to be 3
n = 4                              # set up a value of n to be 4
print(np.zeros(n))                 # create a vector of 4 zeros
print(np.eye(m,n))                 # create a matrix of 3x4 with 1's down the diagonal (an identity matrix). Note no additional (...) around m,n.        
print(np.ones((n,m)))              # create a matrix of 4x3 of ones.
print(np.arange(m*n).reshape(m,n)) # create array with numbers from 0 to m*n and then reshape it into a 3x4 array

[0. 0. 0. 0.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Task 5

Create a matrix filled filled with 1's that has 4 columns and 3 rows. Store this under the variable myArray.

## Creating a matrix: part 2

The second way is define the values. This could be through combining arrays individually and putting them together.

In [20]:
array_0 = np.zeros((2,2))                        # generate 2x2 array with zeros
array_1 = np.ones((2,2))                         # generate 2x2 array with ones
A_1 = np.concatenate((array_0, array_1), axis=0) # concatenate the arrays and increases the number of rows (axis=0) and creates a 4x2 array.
print(A_1, A_1.shape)
A_2 = np.concatenate((array_0, array_1))         # does the same has the line above, as by default arrays are concatenate along axis=0.
print(A_1, A_1.shape)
B_1 = np.concatenate((array_0, array_1), axis=1) # concatenate the arrays and increases the number of columns (axis=1) and creates a 2x4 array.
print(B_1, B_1.shape)

# Alternatively you can also use the horizontal and vertical stack function.
C_v = np.vstack((array_0, array_1))        # vertical stack, which is equivalent to concatenation along the first axis (axis=0) => 4x2 array
print(C_v, C_v.shape)
C_h = np.hstack((array_0, array_1))        # horizontal stack, which is equivalent to concatenation along the second axis (axis=1) => 2x4 array
print(C_h, C_h.shape)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]] (4, 2)
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]] (4, 2)
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]] (2, 4)
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]] (4, 2)
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]] (2, 4)


Vectors or 1D array behave different as they have dimension **N**, only axis=0. For row (**1xN**) and column (**Nx1**) are basically 2D arrays (row x column) and the same operation apply as for matrices.

In [22]:
array_1 = np.array([1,2,3,4])              # set an array 1 of dimension N
array_2 = np.array([3,4,5,6])              # set an array 2 of dimension N
A = np.concatenate((array_1, array_2))     # concatenate into a 1D array with 8 entries, because it stacks along the only available axis. Note np.hstack does the same.
print(A, A.shape)
np.concatenate((array_1, array_2), axis=1) # gives error, because axis=1 does not exist (1D array)

B = np.column_stack((array_1, array_2))    # treats vectors as columns and stacks them => 4x2 matrix
print(B, B.shape)
C = np.vstack((array_1, array_2))          # combine into a 2x4 matrix
print(C, C.shape)
#or
D = np.array([array_1,array_2])            # This is equivalent to np.array([[1,2,3,4], [3,4,5,6]]) 
print(D, D.shape)


[1 2 3 4 3 4 5 6] (8,)
[[1 3]
 [2 4]
 [3 5]
 [4 6]] (4, 2)
[[1 2 3 4]
 [3 4 5 6]] (2, 4)
[[1 2 3 4]
 [3 4 5 6]] (2, 4)


## Task 6
Create a matrix that looks like this. 

```{math}
A=
\begin{bmatrix}
1&5&7\\
4&6&7\\
2&5&7\\
\end{bmatrix}
```

## Task 7

A student has attemped to combine two arrays together to make a larger 4x4 matrix of 1's. 

Their code does not work, can you fix this for them?

In [23]:
 A = np.ones((2,4))
 B = np.ones((4,2))
 
 C = np.concatenate((A,B))
 print(C, C.shape)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 2

## Operations on Matrices
You can multiply element-wise of a matrix by a constant value or indeed two matrices together by using the mathematical operators `+`, `-`, `*`, `/` and `**` (^). 

In [24]:
x=np.array([[1,2,3],[4,5,6]])   # generates a 3 by 2 matrix 
y=np.array([[2,2,2],[3,3,3]])   # generates a 3 by 2 matrix 
print(x*y)                     
print(x/y)
print(x+y)
print(x-y)
print(x**y)

[[ 2  4  6]
 [12 15 18]]
[[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]]
[[3 4 5]
 [7 8 9]]
[[-1  0  1]
 [ 1  2  3]]
[[  1   4   9]
 [ 64 125 216]]


## Task 8

The following section of code should generate a 2x4 matrix. The code should then multiple the first row by a value of 1 and the second by 2.

The code below has a number of problems, try and fix it so it produces the answer of

```{math}
\begin{matrix}
1 & 2 & 3 & 4\\
10& 12& 14& 16\\
\end{matrix}
```

In [25]:
x=np.array([[1,2,3,4],[5,6,7,8]])
y=np.array([1,1,1,1,2,2,2,2])
print(x@y)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 8 is different from 4)

## Selecting elements, rows and columns from an array
You can extract and identify key parts of matrices and vectors through locating the element by coordinates. The number starts at 0 (top right hand corner) and increases down the rows first.

In [26]:
x = np.arange(9).reshape(3,3) + 1  # generates a 3x3 matrix of 1 to 9
print(x)
print(x[0,0])                      # prints the first element
print(x[1,0])                      # prints the second element
print(x[2,:])                      # prints last row
print(x[:,0])                      # prints first column
print(x[1,1:])                     # prints from second element to the end of second row
print(x[-1,2])                     # prints last element of second column equivalent to x[2,2] or x[-1,-1]. Negative numbers mean counting from the end. 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
4
[7 8 9]
[1 4 7]
[5 6]
9


## Task 9

Generate a 4x2 array of random numbers. Then perform the following operations. 
* Multiply each element by 2.5
* Divide the top left element by 3.4


## Things you can do with matrices

A few additional functions you can use with matrices (2D arrays) - as you can see they are similar to vectors (1D arrays). 

In [ ]:
x = np.arange(9).reshape(3,3)   # generates a 3x3 array of 0 to 8

print(np.sin(x))                # calculates the sine (radians) of each value of x
print(np.sqrt(x))               # calculated element-wise the square root

print(x.T)                      # transposes (flips) the array
print(x.sum())                  # sums each element, scalar
print(x.sum(axis=0))            # sums along axis=0, 1D array
print(x.sum(axis=1))            # sums along axis=1, 1D array
print(x.mean())                 # mean/average of each element, scalar
print(x.mean(axis=0))           # mean/average along axis=0, 1D array
print(x.mean(axis=1))           # mean/average along axis=1, 1D array
print(x.size)                   # total number of elements of the array
print(x.shape)                  # shape of array

[[ 0.          0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]
36
[ 9 12 15]
[ 3 12 21]
4.0
[3. 4. 5.]
[1. 4. 7.]
9
(3, 3)


## Task 10
Create an array that goes from $-2\pi$ to $+2\pi$ in 50 equal intervals (i.e. 51 values). Create another array that is the sin of each of the values.

Combine both vectors to form an array of 2 columns and 51 rows. 

## Task 11
Can you write one line of code that sums an array of 50x50 random numbers to a single value?

## Matrix algebra (multiplication) 

The term **scalar multiplication** refers to the product of a number and a matrix. In scalar multiplication, each entry in the matrix is multiplied by the given scalar. You have already done this above using `*`.

In contrast, **matrix or algebra multiplication** refers to the product of two matrices. The order of multiplication is very important.

There are some rules to the matrices you use, 
* The number of **columns of the 1st matrix** must equal the number of **rows of the 2nd matrix**.
* The result will have the same number of **rows as the 1st matrix**, and the same number of **columns as the 2nd matrix**.

The algebra multiplication operator in Python is `@`. See also [Vector multiplication](#vector-multiplications).
 
For example

In [28]:
A=np.array([3,4])                # 1D array with 2 elements
B=np.array([[5,6,7], [8,9,10]])  # 2 x 3 array (3 columns)

C=A@B                            # result is a 1D array. Note: by default a 1D array before '@' is treated as a row vector
print(C)

[47 54 61]


## Task 12
An engineering firm sells 3 types of bolt. 
* A steel bolt that costs 2p each.
* A aluminium bolt that costs 3p each.
* A titanium bolt that costs 10p each.

They sales team sold the following

|         |  Mon | Tue | Wed | Thu | Fri |
|:--------|:----:|:---:|:---:|:---:|:---:|
| Steel   | 5462 | 5233| 4302| 6400| 5900|
| Aluminum| 8433 | 8117| 7826|10105| 9764|
| Titanium| 1218 | 1407| 1503| 1305| 1045|

Create a vector (1D array) for the cost per item, and a matrix (2D array) for the number of items sold.

Using a matrix approach to first work out a vector which contains the total sales in pounds for each day. 

Then use the sum command to work out for the week. 

## Task 13

Create two matrices:

```{math}
A = 
\begin{bmatrix}
1&2\\
3&4\\
\end{bmatrix}
```

```{math}
B = 
\begin{bmatrix}
5&6\\
7&8\\
\end{bmatrix}
```

Find the matrix multiplication of $AB$ and $BA$, showing that the order of multiplication is really important (commutative). 